### ISSUE TITLE
[Question] Why puppeteer was chosen to perform the Google search?

### ISSUE THREAD

**Issue by longnd** [hsnbd/data-scraping#27]
It isn't wrong to use Puppetteer to perform the search in the scraping service:
https://github.com/hsnbd/data-scraping/blob/ae7e241290123b69c87fdfadcbfe9d15509327cc/packages/nest-api/src/scraping-processor-service/keyword-scrape.service.ts#L16-L22

But the solution has some limition
- it is slow as the request requires running actual browser to simulate the user action (searching for specific keyword)
- it is resource intensive to run the browsers, if we want to run multiple message consumers to speed up the process, the impact will be even greater.

A simpler approach could be using an HTTP client (e.g. Axios) to send the search request to Google and receive the response. A simple CURL command should also work. 

But I understand there could be reasons behind the technical decision, thus I would like to understand why you choose the current implementation?

**Comment by hsnbd** [comment]
I was concerned about the AdWords advertisers on the page. I thought Google ads were rendered by JavaScript after the initial load.

**Comment by hsnbd** [comment]
If you suggest using Axios, I will migrate to it. Besides, I also think Puppeteer has a lot of limitations in terms of scalability and consumes high resources.

**Comment by hsnbd** [comment]
Okay, I've figured out that ads also appear during the initial load without JavaScript. Therefore, I can fulfill all the requirements using Axios and Cheerio.
